### ISSUE TITLE
Newsletter for API breaking changes

### ISSUE THREAD

**Issue by fabiomilheiro** [alphagov/notifications-net-client#58]
Not really an issue I'm having but I need to get our team to be notified about changes.

Are the Gov Notify team members notified of such changes?

**Comment by quis** [comment]
Hey @fabiomilheiro if we ever make breaking changes we will publish a new version of the client.

Currently all old versions of the client are still supported. If we ever stop supporting an older version of the client we will:
- contact any affected teams directly
- give those teams time to migrate to the latest version of the client

We also have a changelog which documents what’s in each release:
https://github.com/alphagov/notifications-net-client/blob/master/CHANGELOG.md
