### ISSUE TITLE
Remove "Add the Bintray package source (optional)" from tech docs

### ISSUE THREAD

**Issue by jonathanglassman** [alphagov/notifications-net-client#65]
Removed the "Add the Bintray package source (optional)" section from the tech docs after discussion with @leohemsted and @karlbaker02:

"If you are referencing the GOV.UK Notify client package from a continuous integration (CI) tool, you may need to add the Bintray package source to your Nuget configuration. 

To do this, add a [`nuget.config` file](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file) [external link] to the same folder as your `.sln` file. This is the project root directory by default. The `nuget.config` file must contain the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="$\..\packages" />
  </config>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="bintray" value="https://api.bintray.com/nuget/gov-uk-notify/nuget" />
  </packageSources>
</configuration>
```"

Does this need to be added to the contributing.md file?

**Comment by servingUpAces** [comment]
Thank you Jon. Publishing information has been added to the CONTRIBUTING.md file. We can publish via Jenkins.

**Comment by manos-msdn** [comment]
Please publish to nuget and remove bintray dependency...
